site_name: Fanrri's blog
site_url: https://FanrriN.github.io/blog/
theme:
  name: material

plugins:
  - blog:
      enabled: true
      blog_dir: blog
      blog_toc: true
      post_date_format: medium
      post_url_date_format: yyyy/MM
      post_url_format: "{categories}/{slug}"
      post_slugify_separator: _
      post_excerpt_max_authors: 3
      post_excerpt_max_categories: 3
      categories_name: Articles
      categories_url_format: "category/{slug}"
      categories_allowed:
        - Search
      draft: false

